name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #Seets up JDK
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      #Builds jar with maven
      - name: Build with Maven (fat jar)
        working-directory: PopReports
        run: mvn -B -DskipTests package
      # Uploads shaded jar
      - name: Upload shaded jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: popreports-jar
          path: PopReports/target/*-shaded.jar

      # Build Docker image to prove Dockerfile works
      - name: Build Docker image
        working-directory: PopReports
        run: docker build -t population-app:ci .
