name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build-test-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Run unit tests (host side) for fast feedback
      - name: Test (PopReports)
        run: mvn -B -pl PopReports -am test

      # Build the container using the multi-stage Dockerfile
      - name: Docker build
        run: docker build -t population-reports:ci .
