name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    #runs on latest ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17 # As per the github docs tutorial Temurin is supposed to be used here
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Build & test the PopReports project
      - name: Build with Maven (PopReports)
        run: mvn -B -f PopReports/pom.xml package

      # list what got built
      - name: List target
        run: ls -l PopReports/target

      # Build Docker image at repo root
      - name: Docker build
        run: docker build -t population-reports:ci .
