name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build-test-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Run tests against the module ONLY (no reactor)
      - name: Test (PopReports)
        run: mvn -B -f PopReports/pom.xml test

      # Build image using module-local Dockerfile and context
      - name: Docker build (PopReports)
        run: docker build -t population-reports:ci -f PopReports/Dockerfile PopReports
